export const metadata = {
  title: 'Disclaimer — Market Prime Capital',
  description: 'Disclaimer for Market Prime Capital insurance platform.',
}

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-bg-base py-16 px-4">
      <div className="max-w-4xl mx-auto">
        <div className="mb-12">
          <h1 className="font-display font-bold text-4xl text-tx-primary mb-4">Disclaimer</h1>
          <p className="text-tx-muted">Last updated: April 19, 2026</p>
        </div>

        <div className="space-y-10 text-tx-secondary leading-relaxed">

          <section className="p-6 bg-yellow-500/10 border border-yellow-500/20 rounded-xl">
            <p className="text-yellow-400 font-semibold text-lg">Important Notice</p>
            <p className="mt-2">Market Prime Capital is an insurance aggregator and broker platform. We are not an insurance company. All insurance products listed on our platform are underwritten by IRDAI-registered insurance companies.</p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-2xl text-tx-primary mb-4">1. General Disclaimer</h2>
            <p>The information provided on the Market Prime Capital website is for general informational purposes only. While we strive to keep the information accurate and up to date, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, or suitability of the information for any purpose.</p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-2xl text-tx-primary mb-4">2. Not Financial Advice</h2>
            <p>Nothing on this website constitutes financial, legal, or professional advice. The insurance recommendations generated by our AI system are based on the information you provide and general statistical models. They should not be considered a substitute for professional financial planning. We strongly recommend consulting a certified financial advisor before making significant insurance decisions.</p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-2xl text-tx-primary mb-4">3. Insurance Product Disclaimer</h2>
            <p className="mb-4">Regarding insurance products listed on our platform:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Premium amounts shown are indicative and may vary based on final underwriting</li>
              <li>Policy terms, conditions, and exclusions are as per the respective insurer</li>
              <li>We do not guarantee claim approval — all claims are subject to insurer's terms</li>
              <li>Coverage details are subject to change by the insurer without prior notice</li>
              <li>Past performance of insurance products does not guarantee future results</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display font-semibold text-2xl text-tx-primary mb-4">4. AI Recommendations Disclaimer</h2>
            <p>Our AI-powered recommendation engine uses machine learning algorithms to suggest insurance policies. These recommendations are based on the data you provide and statistical patterns. The accuracy of recommendations depends entirely on the accuracy and completeness of the information you submit. Market Prime Capital is not liable for any decisions made based on AI recommendations.</p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-2xl text-tx-primary mb-4">5. Third-Party Links</h2>
            <p>Our website may contain links to third-party websites. These links are provided for your convenience. We have no control over the content of those sites and accept no responsibility for them or for any loss or damage that may arise from your use of them.</p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-2xl text-tx-primary mb-4">6. Availability of Services</h2>
            <p>We do not guarantee that our website will be available at all times or that it will be free from errors or viruses. We reserve the right to withdraw or modify our services without notice. We shall not be liable if our website is unavailable at any time or for any period.</p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-2xl text-tx-primary mb-4">7. Regulatory Compliance</h2>
            <p>Market Prime Capital operates in compliance with IRDAI (Insurance Regulatory and Development Authority of India) regulations. Our IRDAI registration details are available on our <a href="/irda" className="text-brand-400 hover:underline">IRDAI Registration page</a>. Insurance is a subject matter of solicitation.</p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-2xl text-tx-primary mb-4">8. Limitation of Liability</h2>
            <p>To the fullest extent permitted by applicable law, Market Prime Capital excludes all liability for any direct, indirect, incidental, or consequential loss or damage arising out of or in connection with your use of our website or services, including but not limited to loss of income, profit, or business opportunity.</p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-2xl text-tx-primary mb-4">9. Contact Us</h2>
            <p>For questions about this Disclaimer, contact us:</p>
            <div className="mt-4 p-6 bg-bg-surface border border-bd-subtle rounded-xl">
              <p className="font-semibold text-tx-primary">Market Prime Capital Pvt. Ltd.</p>
              <p className="mt-2">Email: <a href="mailto:legal@marketprimecapital.in" className="text-brand-400 hover:underline">legal@marketprimecapital.in</a></p>
              <p>Phone: +91 1800-XXX-XXXX</p>
              <p>Address: Mumbai, Maharashtra, India</p>
            </div>
          </section>

        </div>
      </div>
    </div>
  )
}